global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert tules configuration
rule_files:
  - 'alert.rules.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
        
scrape_configs:
  - job_name: 'fraud-detection-api'
    static_configs:
      - targets: ['app:8000']  # Using service name from docker-compose
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']