# This workflow will install Python dependencies, run tests and lint with Python 3.10
name: Python Fraud Detection Tests

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add PostgreSQL service for tests
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: frauddb
        ports:
          - 5432:5432
        # Health check to ensure PostgreSQL is available before tests run
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]  # Focus on the version used in production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-cov
        # Install both development and Docker requirements
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements.docker.txt ]; then pip install -r requirements.docker.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Set up test environment
      run: |
        # Initialize test database
        python -m src.db.init_db
      env:
        DATABASE_URL: postgresql://user:password@localhost:5432/frauddb
        MODEL_PATH: ./models/model.joblib
        SCALER_PATH: ./models/amount_scaler.joblib
        CLASS_WEIGHTS_PATH: ./models/class_weights.joblib
    
    - name: Test with pytest
      run: |
        pytest --cov=src --cov-report=xml
      env:
        DATABASE_URL: postgresql://user:password@localhost:5432/frauddb
        MODEL_PATH: ./models/model.joblib
        SCALER_PATH: ./models/amount_scaler.joblib
        CLASS_WEIGHTS_PATH: ./models/class_weights.joblib